import { TourStep } from "@/components/Tour";

export const getTourSteps = (): TourStep[] => {
  return [
    {
      id: "welcome",
      target: "body",
      title: "Welcome to LangChain Enterprise Dashboard! 🎉",
      content: "This interactive tour will guide you through all the powerful features. Let's get started!",
      position: "center",
    },
    {
      id: "sidebar",
      target: "sidebar",
      title: "Navigation Sidebar",
      content: "Use the sidebar to navigate between all 18 features. Each section is fully functional with real datasets and interactive visualizations.",
      position: "right",
    },
    {
      id: "welcome-page",
      target: "welcome-stats",
      title: "Welcome Dashboard",
      content: "The welcome page shows live dataset metrics, quick charts, and data previews. All datasets are auto-loaded on startup.",
      position: "bottom",
    },
    {
      id: "multi-agent",
      target: "[data-tour='multi-agent']",
      title: "Multi-Agent System",
      content: "Intelligent agent routing system. Select an agent or use auto-routing to get specialized responses. Try asking a question!",
      position: "bottom",
    },
    {
      id: "rag",
      target: "[data-tour='rag']",
      title: "Advanced RAG",
      content: "Hybrid search combining semantic and keyword matching. Upload documents and query them with multiple search strategies.",
      position: "bottom",
    },
    {
      id: "tools",
      target: "[data-tour='tools']",
      title: "Tool Execution",
      content: "Execute Python code, scrape websites, or analyze data. Pre-built analysis templates are available for quick insights.",
      position: "bottom",
    },
    {
      id: "analytics",
      target: "[data-tour='analytics']",
      title: "Analytics Dashboard",
      content: "Switch between datasets (E-commerce, Finance, Marketing) and explore interactive charts, metrics, and data tables.",
      position: "bottom",
    },
    {
      id: "demo",
      target: "[data-tour='demo']",
      title: "Enterprise Demo",
      content: "Explore 5 pre-loaded datasets with comprehensive visualizations. Click dataset cards to switch views and see detailed analytics.",
      position: "bottom",
    },
    {
      id: "registry",
      target: "[data-tour='registry']",
      title: "Model Registry",
      content: "Register and manage ML models with versioning, lifecycle management, and performance tracking. View model details and compare versions.",
      position: "bottom",
    },
    {
      id: "ab-testing",
      target: "[data-tour='ab-testing']",
      title: "A/B Testing",
      content: "Create experiments with statistical significance testing. Use the sample size calculator, start experiments, and analyze results with p-values and effect sizes.",
      position: "bottom",
    },
    {
      id: "experiments",
      target: "[data-tour='experiments']",
      title: "Experiment Tracking",
      content: "MLflow-like tracking system. Create runs, log parameters and metrics, and visualize training progress over time.",
      position: "bottom",
    },
    {
      id: "monitoring",
      target: "[data-tour='monitoring']",
      title: "Model Monitoring",
      content: "Track model performance, latency, and detect anomalies. View real-time metrics and alerts for production models.",
      position: "bottom",
    },
    {
      id: "fine-tuning",
      target: "[data-tour='fine-tuning']",
      title: "LLM Fine-Tuning",
      content: "Configure fine-tuning with LoRA, QLoRA, or PEFT methods. Select base models and training parameters for efficient model adaptation.",
      position: "bottom",
    },
    {
      id: "datasets",
      target: "[data-tour='datasets']",
      title: "Datasets & Models",
      content: "View all available datasets, generate custom datasets by industry, and preview data. Each dataset has thousands of realistic records.",
      position: "bottom",
    },
    {
      id: "profiling",
      target: "[data-tour='profiling']",
      title: "Data Profiling",
      content: "Comprehensive data quality analysis including completeness, uniqueness, validity, and consistency scores. Compare datasets side-by-side.",
      position: "bottom",
    },
    {
      id: "statistics",
      target: "[data-tour='statistics']",
      title: "Statistical Analysis",
      content: "Advanced statistical tests and descriptive statistics. View mean, median, standard deviation, and comparison charts.",
      position: "bottom",
    },
    {
      id: "automl",
      target: "[data-tour='automl']",
      title: "AutoML",
      content: "Automated machine learning pipeline. Select datasets, run training, and compare model performance automatically.",
      position: "bottom",
    },
    {
      id: "time-series",
      target: "[data-tour='time-series']",
      title: "Time Series Analysis",
      content: "Time series visualization and trend analysis. View transaction timelines, revenue trends, and aggregated daily data.",
      position: "bottom",
    },
    {
      id: "ensembling",
      target: "[data-tour='ensembling']",
      title: "Model Ensembling",
      content: "Combine multiple models with weighted ensembles. Configure model weights and see improved accuracy through ensemble methods.",
      position: "bottom",
    },
    {
      id: "langchain",
      target: "[data-tour='langchain']",
      title: "LangChain Expertise",
      content: "Explore advanced LangChain patterns, code examples, and best practices. See real-world implementations and integration examples.",
      position: "bottom",
    },
    {
      id: "complete",
      target: "body",
      title: "Tour Complete! 🎊",
      content: "You've explored all the features! Start using the dashboard to analyze data, run experiments, and build ML models. Happy exploring!",
      position: "center",
    },
  ];
};

